
const ficheValidee = {
    DOCUMENT_TYPE: 'Fiche de renseignements',
    DATE: '2025-06-18T00:00:00',
    DATE_DE_DEBUT_DE_CONTRAT: '2025-06-18T00:00:00',
    DATE_DE_FIN_DE_CONTRAT: '2025-06-18T00:00:00',
    SECTEUR_GEOGRAPHIQUE: 'Perpignan',
    NOM_DE_L_ENTREPRISE: 'Dernier Test Promis',
    DENOMINATION_COMMERCIALE: 'test',
    SIRET: null,
    NOM_CARTE_DE_MEMBRE_1: 'LOPEZ',
    PRENOM_CARTE_DE_MEMBRE_1: 'Cédric',
    DATE_DE_NAISSANCE_CARTE_DE_ME: '2025-06-11T00:00:00',
    POSTE_OCCUPE_CARTE_DE_MEMBRE_: 'boss',
    EMAIL_CARTE_DE_MEMBRE_1: '66cedric.lopez@gmail.com',
    NOM_CARTE_DE_MEMBRE_2: null,
    PRENOM_CARTE_DE_MEMBRE_2: null,
    DATE_DE_NAISSANCE_CARTE_DE_M1: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE1: null,
    EMAIL_CARTE_DE_MEMBRE_2: null,
    AVANTAGES_MIS_EN_PLACE_POUR_L: null,
    AVANTAGES_MIS_EN_PLACE_POUR_1: null,
    PAIEMENT___VIREMENT_EN_1_FOIS: 'Non',
    PAIEMENT___DATE_DE_PRELEVEMEN: 'le 01 du mois',
    ACTIVITE_REPRESENTEE: 'tech',
    NOM_CARTE_DE_MEMBRE_3: null,
    PRENOM_CARTE_DE_MEMBRE_3: null,
    DATE_DE_NAISSANCE_CARTE_DE_M2: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE2: null,
    EMAIL_CARTE_DE_MEMBRE_3: null,
    ADRESSE_DE_L_ENTREPRISE: "35 BIS RUE D'ATHENES",
    RCS_DE_L_ENTREPRISE: '123456',
    NOMBRE_DE_CARTES_MEMBRE__: '1',
    PAIEMENT___PRELEVEMENTS_EN_X1: '05',
    NUMERO_D_ADHESION: 199,
    STATUT: 'Fiche Validée',
    ID_FICHE: 462,
    URL_DOCUMENT: 'https://contacts66.docuware.cloud:443/docuware/Platform/WebClient/7eee9134-94d4-442d-b4be-8bed8384872f/Integration?p=V&fc=a128f889-f8f0-415b-88b2-05f6ddee6866&did=462',
    PAYS: null,
    IBAN: 'FR7640618804590004004718121',
    COMMENTAIRE: null,
    BIC: 'CMCIFRPP',
    PAIEMENT_RECURRENT___REPETIT1: null,
    PAIEMENT_PONCTUEL_: null,
    PORTABLE_CARTE_DE_MEMBRE_1: '+33603944938',
    PORTABLE_CARTE_DE_MEMBRE_2: null,
    PORTABLE_CARTE_DE_MEMBRE_3: null,
    AVANTAGES_MIS_EN_PLACE__MEMBR: null,
    DATE_DE_DEBUT_DE_CONTRAT_TXT: '18/06/2025',
    DATE_DE_FIN_DE_CONTRAT_TXT: '18/06/2025',
    PAIEMENT_TOTAL: null,
    CLASSEMENT_1: null,
    CLASSEMENT_2: null,
    CLASSEMENT_3: null,
    NUMERO_DE_FACTURE: null,
    HT: null,
    TVA: null,
    TTC: null,
    ECHEANCE: null,
    DATE_DE_NAISSANCE_CARTE_DE_M3: '11/06/2025',
    INTERVIEW: null,
    ROLL_UP_: null,
    PACK_DEMARRAGE_RS__RESEAUX_SO: null,
    AVANTAGES_MIS_EN_PLACE__GRAND: 'a',
    AVANTAGES_MIS_EN_PLACE__RESER: 'a',
    THEMATIQUES: 'Services à la personne et aux entreprises',
    CARTE_AVANTAGE_HEBERGEUR_QRCO: null,
    LE_MONTANT_DE_L_ADHESION_ANNU: null,
    PAIEMENT_PAR_CHEQUE: 'Non',
    DWEXTENSION: '.',
    DWDOCSIZE: 140208,
    DWDOCID: 462,
    DWSECTIONCOUNT: 2,
    DWSTOREDATETIME: '2025-06-18T09:57:30',
    DWSTOREUSER: 'INVIT',
    DWMODDATETIME: '2025-06-18T09:58:38',
    DWMODUSER: 'JEREMY',
    DWSYS_DOC_URL: 'https://contacts66.docuware.cloud:443/docuware/platform/webclient/7eee9134-94d4-442d-b4be-8bed8384872f/Integration?p=V&fc=a128f889-f8f0-415b-88b2-05f6ddee6866&did=462',
    DWSYS_FC_GUID: 'a128f889-f8f0-415b-88b2-05f6ddee6866',
    DWSYS_ORG_NAME: 'CONTACTS66',
    DWSYS_ORG_DOMAIN: 'https://contacts66.docuware.cloud/docuware',
    DWSYS_ORG_GUID: '7eee9134-94d4-442d-b4be-8bed8384872f'
}

const contratEnvoiSignature = {
    DOCUMENT_TYPE: 'Contrat Premium',
    DATE: '2025-06-18T00:00:00',
    DATE_DE_DEBUT_DE_CONTRAT: null,
    DATE_DE_FIN_DE_CONTRAT: null,
    SECTEUR_GEOGRAPHIQUE: 'Perpignan',
    NOM_DE_L_ENTREPRISE: 'Dernier Test Promis',
    DENOMINATION_COMMERCIALE: 'test',
    SIRET: null,
    NOM_CARTE_DE_MEMBRE_1: 'LOPEZ',
    PRENOM_CARTE_DE_MEMBRE_1: 'Cédric',
    DATE_DE_NAISSANCE_CARTE_DE_ME: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE_: null,
    EMAIL_CARTE_DE_MEMBRE_1: '66cedric.lopez@gmail.com',
    NOM_CARTE_DE_MEMBRE_2: null,
    PRENOM_CARTE_DE_MEMBRE_2: null,
    DATE_DE_NAISSANCE_CARTE_DE_M1: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE1: null,
    EMAIL_CARTE_DE_MEMBRE_2: null,
    AVANTAGES_MIS_EN_PLACE_POUR_L: null,
    AVANTAGES_MIS_EN_PLACE_POUR_1: null,
    PAIEMENT___VIREMENT_EN_1_FOIS: null,
    PAIEMENT___DATE_DE_PRELEVEMEN: null,
    ACTIVITE_REPRESENTEE: null,
    NOM_CARTE_DE_MEMBRE_3: null,
    PRENOM_CARTE_DE_MEMBRE_3: null,
    DATE_DE_NAISSANCE_CARTE_DE_M2: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE2: null,
    EMAIL_CARTE_DE_MEMBRE_3: null,
    ADRESSE_DE_L_ENTREPRISE: "35 BIS RUE D'ATHENES",
    RCS_DE_L_ENTREPRISE: '123456',
    NOMBRE_DE_CARTES_MEMBRE__: null,
    PAIEMENT___PRELEVEMENTS_EN_X1: null,
    NUMERO_D_ADHESION: null,
    STATUT: 'Envoyé en signature',
    ID_FICHE: null,
    URL_DOCUMENT: null,
    PAYS: 'FRANCE',
    IBAN: 'FR7640618804590004004718121',
    COMMENTAIRE: null,
    BIC: 'CMCIFRPP',
    PAIEMENT_RECURRENT___REPETIT1: {
        UpdateStatus: null,
        Values: ['Paiement récurrent / répétitif'],
        currentTag: 0,
        IgnoreInvalidEnums: false
    },
    PAIEMENT_PONCTUEL_: {
        UpdateStatus: null,
        Values: ['Paiement récurrent / répétitif'],
        currentTag: 0,
        IgnoreInvalidEnums: false
    },
    PORTABLE_CARTE_DE_MEMBRE_1: '+33603944938',
    PORTABLE_CARTE_DE_MEMBRE_2: null,
    PORTABLE_CARTE_DE_MEMBRE_3: null,
    AVANTAGES_MIS_EN_PLACE__MEMBR: null,
    DATE_DE_DEBUT_DE_CONTRAT_TXT: '18/06/2025',
    DATE_DE_FIN_DE_CONTRAT_TXT: '18/06/2025',
    PAIEMENT_TOTAL: null,
    CLASSEMENT_1: null,
    CLASSEMENT_2: null,
    CLASSEMENT_3: null,
    NUMERO_DE_FACTURE: null,
    HT: null,
    TVA: null,
    TTC: null,
    ECHEANCE: null,
    DATE_DE_NAISSANCE_CARTE_DE_M3: null,
    INTERVIEW: null,
    ROLL_UP_: null,
    PACK_DEMARRAGE_RS__RESEAUX_SO: null,
    AVANTAGES_MIS_EN_PLACE__GRAND: null,
    AVANTAGES_MIS_EN_PLACE__RESER: null,
    THEMATIQUES: null,
    CARTE_AVANTAGE_HEBERGEUR_QRCO: null,
    LE_MONTANT_DE_L_ADHESION_ANNU: 'nature',
    PAIEMENT_PAR_CHEQUE: null,
    DWEXTENSION: '.pdf',
    DWDOCSIZE: 15199776,
    DWDOCID: 463,
    DWSECTIONCOUNT: 2,
    DWSTOREDATETIME: '2025-06-18T10:01:02',
    DWSTOREUSER: 'JEREMY',
    DWMODDATETIME: '2025-06-18T10:01:57',
    DWMODUSER: 'JEREMY',
    DWSYS_DOC_URL: 'https://contacts66.docuware.cloud:443/docuware/platform/webclient/7eee9134-94d4-442d-b4be-8bed8384872f/Integration?p=V&fc=a128f889-f8f0-415b-88b2-05f6ddee6866&did=463',
    DWSYS_FC_GUID: 'a128f889-f8f0-415b-88b2-05f6ddee6866',
    DWSYS_ORG_NAME: 'CONTACTS66',
    DWSYS_ORG_DOMAIN: 'https://contacts66.docuware.cloud/docuware',
    DWSYS_ORG_GUID: '7eee9134-94d4-442d-b4be-8bed8384872f'
}

const contratSigne = {
    DOCUMENT_TYPE: 'Contrat Premium',
    DATE: '2025-06-18T00:00:00',
    DATE_DE_DEBUT_DE_CONTRAT: null,
    DATE_DE_FIN_DE_CONTRAT: null,
    SECTEUR_GEOGRAPHIQUE: 'Perpignan',
    NOM_DE_L_ENTREPRISE: 'Dernier Test Promis',
    DENOMINATION_COMMERCIALE: 'test',
    SIRET: null,
    NOM_CARTE_DE_MEMBRE_1: 'LOPEZ',
    PRENOM_CARTE_DE_MEMBRE_1: 'Cédric',
    DATE_DE_NAISSANCE_CARTE_DE_ME: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE_: null,
    EMAIL_CARTE_DE_MEMBRE_1: '66cedric.lopez@gmail.com',
    NOM_CARTE_DE_MEMBRE_2: null,
    PRENOM_CARTE_DE_MEMBRE_2: null,
    DATE_DE_NAISSANCE_CARTE_DE_M1: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE1: null,
    EMAIL_CARTE_DE_MEMBRE_2: null,
    AVANTAGES_MIS_EN_PLACE_POUR_L: null,
    AVANTAGES_MIS_EN_PLACE_POUR_1: null,
    PAIEMENT___VIREMENT_EN_1_FOIS: null,
    PAIEMENT___DATE_DE_PRELEVEMEN: null,
    ACTIVITE_REPRESENTEE: null,
    NOM_CARTE_DE_MEMBRE_3: null,
    PRENOM_CARTE_DE_MEMBRE_3: null,
    DATE_DE_NAISSANCE_CARTE_DE_M2: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE2: null,
    EMAIL_CARTE_DE_MEMBRE_3: null,
    ADRESSE_DE_L_ENTREPRISE: "35 BIS RUE D'ATHENES",
    RCS_DE_L_ENTREPRISE: '123456',
    NOMBRE_DE_CARTES_MEMBRE__: null,
    PAIEMENT___PRELEVEMENTS_EN_X1: null,
    NUMERO_D_ADHESION: 199,
    STATUT: 'Contrat signé',
    ID_FICHE: 462,
    URL_DOCUMENT: null,
    PAYS: 'FRANCE',
    IBAN: 'FR7640618804590004004718121',
    COMMENTAIRE: null,
    BIC: 'CMCIFRPP',
    PAIEMENT_RECURRENT___REPETIT1: {
        UpdateStatus: null,
        Values: ['Paiement récurrent / répétitif'],
        currentTag: 0,
        IgnoreInvalidEnums: false
    },
    PAIEMENT_PONCTUEL_: {
        UpdateStatus: null,
        Values: ['Paiement récurrent / répétitif'],
        currentTag: 0,
        IgnoreInvalidEnums: false
    },
    PORTABLE_CARTE_DE_MEMBRE_1: '+33603944938',
    PORTABLE_CARTE_DE_MEMBRE_2: null,
    PORTABLE_CARTE_DE_MEMBRE_3: null,
    AVANTAGES_MIS_EN_PLACE__MEMBR: null,
    DATE_DE_DEBUT_DE_CONTRAT_TXT: '18/06/2025',
    DATE_DE_FIN_DE_CONTRAT_TXT: '18/06/2025',
    PAIEMENT_TOTAL: null,
    CLASSEMENT_1: null,
    CLASSEMENT_2: null,
    CLASSEMENT_3: null,
    NUMERO_DE_FACTURE: null,
    HT: null,
    TVA: null,
    TTC: null,
    ECHEANCE: null,
    DATE_DE_NAISSANCE_CARTE_DE_M3: null,
    INTERVIEW: null,
    ROLL_UP_: null,
    PACK_DEMARRAGE_RS__RESEAUX_SO: null,
    AVANTAGES_MIS_EN_PLACE__GRAND: null,
    AVANTAGES_MIS_EN_PLACE__RESER: null,
    THEMATIQUES: null,
    CARTE_AVANTAGE_HEBERGEUR_QRCO: null,
    LE_MONTANT_DE_L_ADHESION_ANNU: 'nature',
    PAIEMENT_PAR_CHEQUE: null,
    DWEXTENSION: '.pdf',
    DWDOCSIZE: 15802000,
    DWDOCID: 463,
    DWSECTIONCOUNT: 3,
    DWSTOREDATETIME: '2025-06-18T10:01:02',
    DWSTOREUSER: 'JEREMY',
    DWMODDATETIME: '2025-06-18T11:21:49',
    DWMODUSER: 'ADMIN',
    DWSYS_DOC_URL: 'https://contacts66.docuware.cloud:443/docuware/platform/webclient/7eee9134-94d4-442d-b4be-8bed8384872f/Integration?p=V&fc=a128f889-f8f0-415b-88b2-05f6ddee6866&did=463',
    DWSYS_FC_GUID: 'a128f889-f8f0-415b-88b2-05f6ddee6866',
    DWSYS_ORG_NAME: 'CONTACTS66',
    DWSYS_ORG_DOMAIN: 'https://contacts66.docuware.cloud/docuware',
    DWSYS_ORG_GUID: '7eee9134-94d4-442d-b4be-8bed8384872f'
}