import { createThirdparty } from '../src/services/thirdparties.service.js';
import dotenv from 'dotenv';
dotenv.config();
// Test simple avec seulement le champ obligatoire
const testData = {
    DOCUMENT_TYPE: 'Fiche de renseignements',
    DATE: '2025-06-16T00:00:00',
    DATE_DE_DEBUT_DE_CONTRAT: null,
    DATE_DE_FIN_DE_CONTRAT: null,
    SECTEUR_GEOGRAPHIQUE: 'Perpignan',
    NOM_DE_L_ENTREPRISE: 'Test ERP',
    DENOMINATION_COMMERCIALE: 'Test ERP',
    SIRET: null,
    NOM_CARTE_DE_MEMBRE_1: 'Lopez',
    PRENOM_CARTE_DE_MEMBRE_1: 'Cédric',
    DATE_DE_NAISSANCE_CARTE_DE_ME: '1987-08-12T00:00:00',
    POSTE_OCCUPE_CARTE_DE_MEMBRE_: 'Big Boss',
    EMAIL_CARTE_DE_MEMBRE_1: '66cedric.lopez@gmail.com',
    NOM_CARTE_DE_MEMBRE_2: null,
    PRENOM_CARTE_DE_MEMBRE_2: null,
    DATE_DE_NAISSANCE_CARTE_DE_M1: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE1: null,
    EMAIL_CARTE_DE_MEMBRE_2: null,
    AVANTAGES_MIS_EN_PLACE_POUR_L: null,
    AVANTAGES_MIS_EN_PLACE_POUR_1: null,
    PAIEMENT___VIREMENT_EN_1_FOIS: 'Oui',
    PAIEMENT___DATE_DE_PRELEVEMEN: null,
    ACTIVITE_REPRESENTEE: 'Test activité',
    NOM_CARTE_DE_MEMBRE_3: null,
    PRENOM_CARTE_DE_MEMBRE_3: null,
    DATE_DE_NAISSANCE_CARTE_DE_M2: null,
    POSTE_OCCUPE_CARTE_DE_MEMBRE2: null,
    EMAIL_CARTE_DE_MEMBRE_3: null,
    ADRESSE_DE_L_ENTREPRISE: "35 BIS RUE D'ATHENES",
    RCS_DE_L_ENTREPRISE: '45279195700031',
    NOMBRE_DE_CARTES_MEMBRE__: '1',
    PAIEMENT___PRELEVEMENTS_EN_X1: null,
    NUMERO_D_ADHESION: 195,
    STATUT: 'Fiche à valider',
    ID_FICHE: null,
    URL_DOCUMENT: null,
    PAYS: null,
    IBAN: null,
    COMMENTAIRE: null,
    BIC: null,
    PAIEMENT_RECURRENT___REPETIT1: null,
    PAIEMENT_PONCTUEL_: null,
    PORTABLE_CARTE_DE_MEMBRE_1: '+33603944938',
    PORTABLE_CARTE_DE_MEMBRE_2: null,
    PORTABLE_CARTE_DE_MEMBRE_3: null,
    AVANTAGES_MIS_EN_PLACE__MEMBR: null,
    DATE_DE_DEBUT_DE_CONTRAT_TXT: null,
    DATE_DE_FIN_DE_CONTRAT_TXT: null,
    PAIEMENT_TOTAL: null,
    CLASSEMENT_1: null,
    CLASSEMENT_2: null,
    CLASSEMENT_3: null,
    NUMERO_DE_FACTURE: null,
    HT: null,
    TVA: null,
    TTC: null,
    ECHEANCE: null,
    DATE_DE_NAISSANCE_CARTE_DE_M3: null,
    INTERVIEW: null,
    ROLL_UP_: null,
    PACK_DEMARRAGE_RS__RESEAUX_SO: null,
    AVANTAGES_MIS_EN_PLACE__GRAND: 'test 1',
    AVANTAGES_MIS_EN_PLACE__RESER: 'test 2',
    THEMATIQUES: 'Services à la personne et aux entreprises',
    CARTE_AVANTAGE_HEBERGEUR_QRCO: null,
    LE_MONTANT_DE_L_ADHESION_ANNU: null,
    PAIEMENT_PAR_CHEQUE: null,
    DWEXTENSION: '.',
    DWDOCSIZE: 140096,
    DWDOCID: 453,
    DWSECTIONCOUNT: 2,
    DWSTOREDATETIME: '2025-06-16T08:47:26',
    DWSTOREUSER: 'INVIT',
    DWMODDATETIME: '2025-06-16T08:47:26',
    DWMODUSER: 'INVIT',
    DWSYS_DOC_URL: 'https://contacts66.docuware.cloud:443/docuware/platform/webclient/7eee9134-94d4-442d-b4be-8bed8384872f/Integration?p=V&fc=a128f889-f8f0-415b-88b2-05f6ddee6866&did=453',
    DWSYS_FC_GUID: 'a128f889-f8f0-415b-88b2-05f6ddee6866',
    DWSYS_ORG_NAME: 'CONTACTS66',
    DWSYS_ORG_DOMAIN: 'https://contacts66.docuware.cloud/docuware',
    DWSYS_ORG_GUID: '7eee9134-94d4-442d-b4be-8bed8384872f'
};

console.log('Test avec données minimales:', testData);

try {
    const result = await createThirdparty(testData);
    console.log('Succès:', result);
} catch (error) {
    console.error('Erreur:', error.message);
} 